ALTER TABLE public.clients
  ADD COLUMN IF NOT EXISTS client_link TEXT,
  ADD COLUMN IF NOT EXISTS posts_per_day INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS videos_per_day INTEGER NOT NULL DEFAULT 0;