// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddztohwsizuznfmjmkfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkenRvaHdzaXp1em5mbWpta2ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE0OTk5OTksImV4cCI6MjA5NzA3NTk5OX0.f1I02CnlyimM3qeDTmlAQLyuJdT-Y_PvjOk3oysdfl8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});